title: Big Data Analytics for Health and Medicine
description: 2<sup>nd</sup> International Workshop on Big Data Analytics for Health and Medicine (BDA4HM 2023) 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
