title: Big Data Analytics for Health and Medicine
description: 1<sup>st</sup> International Workshop on Big Data Analytics for Health and Medicine (BDA4HM 2022) 
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
